import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import { env } from "~/env.mjs";
import { Button, ButtonGroup } from '@chakra-ui/react'
import router, { useRouter } from "next/router";

export default function Home() {
  useRouter
  return (
    <>
      <Head>
        <title>Admin app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>{env.NEXT_PUBLIC_BACKEND_BASE_URL}</h1>
        </div>
        <Button colorScheme='teal' size='lg' 
          onClick={()=>{
            router.push("/login")
          }}>
          Button
        </Button>
      </main>
    </>
  );
}
