import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import { env } from "~/env.mjs";
import { Button, ButtonGroup, Container, Heading } from '@chakra-ui/react'
import router, { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  useRouter
  return (
    <>
      <Head>
        <title>Admin app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
        <Heading>Mis ventas</Heading>
        <ButtonGroup>
          <Button colorScheme='teal'
            onClick={()=>{
              router.push("/login")
            }}>
            Iniciar sesion
          </Button>

          <Button colorScheme='red' 
            onClick={()=>{
              axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {
                withCredentials: true
              })
            }}>
            Obtener ventas
          </Button>

          <Button colorScheme='purple' 
            onClick={()=>{
              axios.post(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`, {
                operation_date: new Date(),
                total_amount: 5555
              }, {
                withCredentials: true
              })
            }}>
            Crear venta
          </Button>


        </ButtonGroup>
      </Container>
    </>
  );
}
